// flow-typed signature: 1587f6f32671d16e56cacafaefeccfd4
// flow-typed version: <<STUB>>/@sendgrid/client_v6.3.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sendgrid/client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sendgrid/client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sendgrid/client/src/classes/client' {
  declare module.exports: any;
}

declare module '@sendgrid/client/src/client' {
  declare module.exports: any;
}

declare module '@sendgrid/client/src/client.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sendgrid/client/index' {
  declare module.exports: $Exports<'@sendgrid/client'>;
}
declare module '@sendgrid/client/index.js' {
  declare module.exports: $Exports<'@sendgrid/client'>;
}
declare module '@sendgrid/client/src/classes/client.js' {
  declare module.exports: $Exports<'@sendgrid/client/src/classes/client'>;
}
declare module '@sendgrid/client/src/client.js' {
  declare module.exports: $Exports<'@sendgrid/client/src/client'>;
}
declare module '@sendgrid/client/src/client.spec.js' {
  declare module.exports: $Exports<'@sendgrid/client/src/client.spec'>;
}
