// flow-typed signature: 29e4bca5b042814aac7afd5d9a855d98
// flow-typed version: <<STUB>>/sequelize-mock_v^0.10.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sequelize-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sequelize-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sequelize-mock/scripts/doc-gen' {
  declare module.exports: any;
}

declare module 'sequelize-mock/scripts/version' {
  declare module.exports: any;
}

declare module 'sequelize-mock/src/data-types' {
  declare module.exports: any;
}

declare module 'sequelize-mock/src/errors' {
  declare module.exports: any;
}

declare module 'sequelize-mock/src/index' {
  declare module.exports: any;
}

declare module 'sequelize-mock/src/instance' {
  declare module.exports: any;
}

declare module 'sequelize-mock/src/model' {
  declare module.exports: any;
}

declare module 'sequelize-mock/src/queryinterface' {
  declare module.exports: any;
}

declare module 'sequelize-mock/src/sequelize' {
  declare module.exports: any;
}

declare module 'sequelize-mock/src/utils' {
  declare module.exports: any;
}

declare module 'sequelize-mock/test/data-types.spec' {
  declare module.exports: any;
}

declare module 'sequelize-mock/test/errors.spec' {
  declare module.exports: any;
}

declare module 'sequelize-mock/test/instance.spec' {
  declare module.exports: any;
}

declare module 'sequelize-mock/test/model.spec' {
  declare module.exports: any;
}

declare module 'sequelize-mock/test/queryinterface.spec' {
  declare module.exports: any;
}

declare module 'sequelize-mock/test/sequelize.spec' {
  declare module.exports: any;
}

declare module 'sequelize-mock/test/utils.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sequelize-mock/scripts/doc-gen.js' {
  declare module.exports: $Exports<'sequelize-mock/scripts/doc-gen'>;
}
declare module 'sequelize-mock/scripts/version.js' {
  declare module.exports: $Exports<'sequelize-mock/scripts/version'>;
}
declare module 'sequelize-mock/src/data-types.js' {
  declare module.exports: $Exports<'sequelize-mock/src/data-types'>;
}
declare module 'sequelize-mock/src/errors.js' {
  declare module.exports: $Exports<'sequelize-mock/src/errors'>;
}
declare module 'sequelize-mock/src/index.js' {
  declare module.exports: $Exports<'sequelize-mock/src/index'>;
}
declare module 'sequelize-mock/src/instance.js' {
  declare module.exports: $Exports<'sequelize-mock/src/instance'>;
}
declare module 'sequelize-mock/src/model.js' {
  declare module.exports: $Exports<'sequelize-mock/src/model'>;
}
declare module 'sequelize-mock/src/queryinterface.js' {
  declare module.exports: $Exports<'sequelize-mock/src/queryinterface'>;
}
declare module 'sequelize-mock/src/sequelize.js' {
  declare module.exports: $Exports<'sequelize-mock/src/sequelize'>;
}
declare module 'sequelize-mock/src/utils.js' {
  declare module.exports: $Exports<'sequelize-mock/src/utils'>;
}
declare module 'sequelize-mock/test/data-types.spec.js' {
  declare module.exports: $Exports<'sequelize-mock/test/data-types.spec'>;
}
declare module 'sequelize-mock/test/errors.spec.js' {
  declare module.exports: $Exports<'sequelize-mock/test/errors.spec'>;
}
declare module 'sequelize-mock/test/instance.spec.js' {
  declare module.exports: $Exports<'sequelize-mock/test/instance.spec'>;
}
declare module 'sequelize-mock/test/model.spec.js' {
  declare module.exports: $Exports<'sequelize-mock/test/model.spec'>;
}
declare module 'sequelize-mock/test/queryinterface.spec.js' {
  declare module.exports: $Exports<'sequelize-mock/test/queryinterface.spec'>;
}
declare module 'sequelize-mock/test/sequelize.spec.js' {
  declare module.exports: $Exports<'sequelize-mock/test/sequelize.spec'>;
}
declare module 'sequelize-mock/test/utils.spec.js' {
  declare module.exports: $Exports<'sequelize-mock/test/utils.spec'>;
}
